### ISSUE TITLE
which php/os is supported?

### ISSUE THREAD

**Issue by machado2** [spreadit/spreadit#42]
Is it compatible with php 5.4? I was trying to run the program in a centos 7 machine, but there were some php errors during the "php artisan" step of the installation.

**Comment by whackashoe** [comment]
I believe it is, though it isn't tested. Could you list the console output here?

**Comment by machado2** [comment]
First there were two of these erros, I was able to correct using a temporary variable:

PHP Fatal error:  Can't use function return value in write context in /data/spreadit/spreadit/app/libs/ViewComposers/ViewComposers.php on line 135

Then I reached this one:

PHP Fatal error:  Call to undefined function Symfony\Component\Console\mb_convert_variables() in /data/spreadit/spreadit/vendor/symfony/console/Symfony/Component/Console/Application.php on line 1154

**Comment by whackashoe** [comment]
Hm - yes there may be some small differences due to how 5.5 interprets empty and such that you may need changes. I've only tested on 5.5 thus far, a patch would be appreciated!

On the second error, according to this [stackoverflow answer](http://stackoverflow.com/questions/28971812/laravel-call-to-undefined-function-symfony-component-console-mb-convert-variabl):

```
From datasage comment:

You need to install a package named something like php-mbstring. Name may vary depending on the extact version of linux.
Example:

sudo yum install php55-mbstring

```

Hopefully that helps, let me know!

**Comment by machado2** [comment]
I upgraded to php 5.5 and it worked after installing some missing php packages.

Now my I have some erros about missing static files like '/public/assets/img/sprite-spreadit.png'.

**Comment by whackashoe** [comment]
Ok cool.

And yeah, right now spreadit is being overhauled to use reddit css themes so a lot on frontend is broken, you can checkout an earlier commit to play around if that isn't your thing.
